import { COBUILD_PROJECT_ID, COBUILD_PROJECT_ID_BIGINT } from "@cobuild/wire";

export const COBUILD_JUICEBOX_PROJECT_ID = COBUILD_PROJECT_ID;
export const COBUILD_JUICEBOX_PROJECT_ID_BIGINT = COBUILD_PROJECT_ID_BIGINT;
