import type { DaoEvent } from "./dao-flow-types";

export const DEMO_EVENTS: DaoEvent[] = [
  {
    t: 0,
    type: "GOAL_CREATE",
    id: "g1",
    title: "Build a million-person DAO",
    deadline: 70,
    by: "human1",
  },
  { t: 0, type: "GOAL_DEPOSIT", from: "donor", amount: 100_000 },
  { t: 2, type: "NOTE", text: "Subgoals defined." },

  {
    t: 5,
    type: "BUDGET_PROPOSE",
    id: "b1",
    title: "Ship v1 protocol contracts",
    minBudget: 12_000,
    maxBudget: 30_000,
    fundingDeadline: 25,
    executionDuration: 30,
    by: "human1",
  },
  {
    t: 6,
    type: "BUDGET_PROPOSE",
    id: "b2",
    title: "Launch governance pilot",
    minBudget: 8_000,
    maxBudget: 18_000,
    fundingDeadline: 25,
    executionDuration: 25,
    by: "bot1",
  },
  {
    t: 7,
    type: "BUDGET_PROPOSE",
    id: "b3",
    title: "Onboard first 1,000 members",
    minBudget: 8_000,
    maxBudget: 14_000,
    fundingDeadline: 50,
    executionDuration: 25,
    by: "human2",
  },
  {
    t: 11,
    type: "BUDGET_PROPOSE",
    id: "b4",
    title: "Publish contributor handbook",
    minBudget: 5_000,
    maxBudget: 12_000,
    fundingDeadline: 40,
    executionDuration: 18,
    by: "bot1",
  },
  {
    t: 12,
    type: "BUDGET_PROPOSE",
    id: "b5",
    title: "Launch governance dashboard",
    minBudget: 7_000,
    maxBudget: 16_000,
    fundingDeadline: 45,
    executionDuration: 24,
    by: "human1",
  },

  { t: 8, type: "BUDGET_TCR_RESOLVE", id: "b1", result: "LISTED" },
  { t: 9, type: "BUDGET_TCR_RESOLVE", id: "b2", result: "LISTED" },
  { t: 10, type: "BUDGET_TCR_RESOLVE", id: "b3", result: "LISTED" },
  { t: 13, type: "BUDGET_TCR_RESOLVE", id: "b4", result: "LISTED" },
  { t: 14, type: "BUDGET_TCR_RESOLVE", id: "b5", result: "LISTED" },

  { t: 8, type: "STAKE_WEIGHT_SET", nodeId: "b1", actor: "human1", weight: 20 },
  { t: 9, type: "STAKE_WEIGHT_SET", nodeId: "b1", actor: "bot1", weight: 20 },
  { t: 10, type: "STAKE_WEIGHT_SET", nodeId: "b1", actor: "bot1", weight: 20 },
  { t: 12, type: "STAKE_WEIGHT_SET", nodeId: "b2", actor: "bot1", weight: 20 },
  { t: 13, type: "STAKE_WEIGHT_SET", nodeId: "b2", actor: "human2", weight: 20 },
  { t: 14, type: "STAKE_WEIGHT_SET", nodeId: "b2", actor: "bot1", weight: 20 },

  { t: 11, type: "STAKE_WEIGHT_SET", nodeId: "b3", actor: "human2", weight: 20 },
  { t: 12, type: "STAKE_WEIGHT_SET", nodeId: "b3", actor: "human1", weight: 20 },
  { t: 13, type: "STAKE_WEIGHT_SET", nodeId: "b3", actor: "bot1", weight: 20 },

  { t: 17, type: "STAKE_WEIGHT_SET", nodeId: "b4", actor: "bot1", weight: 20 },
  { t: 18, type: "STAKE_WEIGHT_SET", nodeId: "b4", actor: "human1", weight: 20 },
  { t: 19, type: "STAKE_WEIGHT_SET", nodeId: "b4", actor: "bot1", weight: 20 },

  { t: 20, type: "STAKE_WEIGHT_SET", nodeId: "b5", actor: "human2", weight: 20 },
  { t: 21, type: "STAKE_WEIGHT_SET", nodeId: "b5", actor: "bot1", weight: 20 },
  { t: 22, type: "STAKE_WEIGHT_SET", nodeId: "b5", actor: "human1", weight: 20 },

  { t: 18, type: "GOAL_DEPOSIT", from: "donor", amount: 20_000 },

  { t: 34, type: "NOTE", text: "Subgoal funded." },
  {
    t: 35,
    type: "MECH_PROPOSE",
    id: "m1",
    parentBudgetId: "b1",
    mechType: "FLOW",
    title: "Core engineering stream",
    payees: [{ id: "p1", title: "Protocol Guild" }],
    by: "system",
  },
  {
    t: 36,
    type: "MECH_PROPOSE",
    id: "m2",
    parentBudgetId: "b1",
    mechType: "ROUND",
    title: "Legitimacy experiments",
    payees: [{ id: "p2", title: "Civic Collective" }],
    by: "system",
  },
  { t: 37, type: "MECH_TCR_RESOLVE", id: "m1", result: "LISTED" },
  { t: 38, type: "MECH_TCR_RESOLVE", id: "m2", result: "LISTED" },

  { t: 39, type: "STAKE_WEIGHT_SET", nodeId: "m1", actor: "human1", weight: 15 },
  { t: 40, type: "STAKE_WEIGHT_SET", nodeId: "m2", actor: "bot1", weight: 10 },

  { t: 41, type: "STAKE_WEIGHT_SET", nodeId: "b1", actor: "human1", weight: 0 },
  { t: 42, type: "NOTE", text: "Stake removed." },

  { t: 45, type: "NOTE", text: "Subgoal funded (cap soon)." },
  {
    t: 46,
    type: "MECH_PROPOSE",
    id: "m3",
    parentBudgetId: "b3",
    mechType: "FLOW",
    title: "Onboarding ops",
    payees: [
      { id: "p3", title: "Community Hosts" },
      { id: "p4", title: "Growth Ops" },
    ],
    by: "system",
  },
  { t: 47, type: "MECH_TCR_RESOLVE", id: "m3", result: "LISTED" },
  { t: 48, type: "STAKE_WEIGHT_SET", nodeId: "m3", actor: "human2", weight: 20 },

  { t: 50, type: "BUDGET_RESOLVE", id: "b1", result: "SUCCEEDED" },
  { t: 52, type: "NOTE", text: "Subgoal completed." },
  { t: 56, type: "BUDGET_RESOLVE", id: "b3", result: "FAILED" },

  { t: 66, type: "NOTE", text: "Goal verified." },
  { t: 68, type: "GOAL_RESOLVE", result: "SUCCEEDED" },
];

export const REPLACEMENT_BUDGET_TITLES = [
  "Run community governance workshops",
  "Ship grants review rubric",
  "Launch builder spotlight series",
  "Deliver contributor analytics v1",
  "Publish ecosystem roadmap",
];
