name: Bug report
description: Report a reproducible bug in Cobuild.
title: "[bug]: "
labels:
  - "type: bug"
  - "status: needs-repro"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report.

        Issues are reserved for actionable, reproducible bugs.
        For questions and setup help, use Discussions:
        https://github.com/cobuildwithus/interface/discussions

  - type: input
    id: version
    attributes:
      label: Version or commit
      description: Share the deployed version or commit SHA.
      placeholder: "e.g. main@abc1234"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected area
      options:
        - Web UI
        - API routes
        - Onchain/contracts integration
        - Auth/session
        - CI/tooling
        - Documentation
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Provide exact steps so maintainers can reproduce quickly.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs, screenshots, or traces
      description: Paste relevant console output, screenshots, or request traces.
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, browser, wallet/client, and any other relevant context.
      placeholder: |
        - OS:
        - Browser:
        - Wallet:
        - Network:
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Confirmation
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: This is not a security vulnerability report.
          required: true
