import { Users, HeartPulse, ShieldCheck, Code, Leaf, Sparkles, Radio } from "lucide-react";
import type { GoalTopicOption } from "@/components/common/goal-topic-toggle";
import type { DaoEvent } from "@/components/visuals/dao-flow-diagram/dao-flow-diagram";
import type { BudgetTemplate, StakePlan, TopicConfig } from "./types";

const BUDGET_SCHEDULE = [
  {
    id: "b1",
    proposeAt: 5,
    resolveAt: 8,
    minBudget: 12_000,
    maxBudget: 30_000,
    fundingDeadline: 25,
    executionDuration: 60,
    by: "human1",
  },
  {
    id: "b2",
    proposeAt: 6,
    resolveAt: 9,
    minBudget: 8_000,
    maxBudget: 18_000,
    fundingDeadline: 25,
    executionDuration: 60,
    by: "bot1",
  },
  {
    id: "b3",
    proposeAt: 7,
    resolveAt: 10,
    minBudget: 8_000,
    maxBudget: 14_000,
    fundingDeadline: 50,
    executionDuration: 55,
    by: "human2",
  },
  {
    id: "b4",
    proposeAt: 11,
    resolveAt: 13,
    minBudget: 5_000,
    maxBudget: 12_000,
    fundingDeadline: 40,
    executionDuration: 50,
    by: "bot1",
  },
  {
    id: "b5",
    proposeAt: 12,
    resolveAt: 14,
    minBudget: 7_000,
    maxBudget: 16_000,
    fundingDeadline: 45,
    executionDuration: 55,
    by: "human1",
  },
] satisfies BudgetTemplate[];

const STAKE_PLAN: StakePlan = {
  b1: [
    { t: 8, actor: "human1", weight: 20 },
    { t: 9, actor: "bot1", weight: 20 },
    { t: 10, actor: "bot1", weight: 20 },
  ],
  b2: [
    { t: 12, actor: "bot1", weight: 20 },
    { t: 13, actor: "human2", weight: 20 },
    { t: 14, actor: "bot1", weight: 20 },
  ],
  b3: [
    { t: 11, actor: "human2", weight: 20 },
    { t: 12, actor: "human1", weight: 20 },
    { t: 13, actor: "bot1", weight: 20 },
  ],
  b4: [
    { t: 17, actor: "bot1", weight: 20 },
    { t: 18, actor: "human1", weight: 20 },
    { t: 19, actor: "bot1", weight: 20 },
  ],
  b5: [
    { t: 20, actor: "human2", weight: 20 },
    { t: 21, actor: "bot1", weight: 20 },
    { t: 22, actor: "human1", weight: 20 },
  ],
};

export const TOPICS = [
  {
    id: "dao",
    label: "DAO",
    blurb: "Build shared ownership for cultural missions.",
    goalTitle: "Build a million-person DAO",
    note: "Subgoals for building the DAO.",
    icon: Users,
    budgets: [
      "Draft governance charter",
      "Design token model",
      "Build proposal system",
      "Create voting UI",
      "Write onboarding docs",
      "Set up Discord bot",
      "Build treasury dashboard",
      "Create contributor roles",
      "Design dispute process",
      "Launch test governance",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Core protocol stream",
        payees: [{ id: "p1", title: "Protocol Guild" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Legitimacy experiments",
        payees: [{ id: "p2", title: "Civic Collective" }],
      },
    ],
    flowTasks: [
      "Charter ops",
      "Token modeling",
      "Proposal support",
      "Voting ops",
      "Onboarding stream",
      "Bot maintenance",
      "Treasury monitoring",
      "Role management",
      "Dispute resolution",
      "Governance testing",
    ],
    roundTasks: [
      "Charter grants",
      "Token bounties",
      "Proposal experiments",
      "Voting improvements",
      "Onboarding grants",
      "Bot bounties",
      "Dashboard grants",
      "Role proposals",
      "Mediation grants",
      "Governance simulations",
    ],
  },
  {
    id: "longevity",
    label: "Longevity",
    blurb: "Run a massive distributed study on what actually extends healthspan.",
    goalTitle: "Run a million-person longevity study",
    note: "Subgoals for building the study.",
    icon: HeartPulse,
    budgets: [
      "Draft study protocol",
      "Design consent flow",
      "Build data intake form",
      "Create tracking dashboard",
      "Recruit first coordinators",
      "Set up data pipeline",
      "Partner with lab network",
      "Build reminder system",
      "Create participant FAQ",
      "Launch pilot cohort",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Participant onboarding",
        payees: [{ id: "p1", title: "Enrollment Ops" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Regional coordinator grants",
        payees: [{ id: "p2", title: "Local Chapters" }],
      },
    ],
    flowTasks: [
      "Protocol review",
      "Consent ops",
      "Data intake",
      "Dashboard monitoring",
      "Coordinator training",
      "Pipeline maintenance",
      "Lab liaison",
      "Reminder ops",
      "FAQ maintenance",
      "Cohort support",
    ],
    roundTasks: [
      "Protocol grants",
      "Consent experiments",
      "Form grants",
      "Analytics bounties",
      "Coordinator grants",
      "Data bounties",
      "Lab grants",
      "Engagement experiments",
      "FAQ bounties",
      "Pilot grants",
    ],
  },
  {
    id: "privacy",
    label: "Privacy",
    blurb: "Help people switch to private, encrypted communication tools.",
    goalTitle: "Migrate 1 million to encrypted messaging",
    note: "Subgoals for driving adoption.",
    icon: ShieldCheck,
    budgets: [
      "Write beginner guide",
      "Build contact importer",
      "Create video tutorials",
      "Translate to Spanish",
      "Train first ambassadors",
      "Build progress tracker",
      "Create family guide",
      "Set up help hotline",
      "Build group migration tool",
      "Launch referral program",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Onboarding support",
        payees: [{ id: "p1", title: "Migration Helpers" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Local ambassador grants",
        payees: [{ id: "p2", title: "Privacy Advocates" }],
      },
    ],
    flowTasks: [
      "Guide maintenance",
      "Importer ops",
      "Tutorial production",
      "Translation coordination",
      "Ambassador training",
      "Tracker ops",
      "Family support",
      "Hotline staffing",
      "Migration maintenance",
      "Referral tracking",
    ],
    roundTasks: [
      "Guide bounties",
      "Importer grants",
      "Tutorial challenges",
      "Translation bounties",
      "Ambassador grants",
      "Analytics grants",
      "Family outreach",
      "Support grants",
      "Migration bounties",
      "Referral experiments",
    ],
  },
  {
    id: "open-source",
    label: "Open Source",
    blurb: "Sustain critical digital infrastructure and maintainers.",
    goalTitle: "Pay 10,000 maintainers fairly",
    note: "Subgoals for funding maintainers.",
    icon: Code,
    budgets: [
      "Build application form",
      "Define eligibility rules",
      "Set up Stripe payouts",
      "Create project directory",
      "Build review dashboard",
      "Write maintainer FAQ",
      "Set up tax docs flow",
      "Create stipend tiers",
      "Build impact tracker",
      "Launch first cohort",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Maintainer stream",
        payees: [{ id: "p1", title: "Infra Maintainers" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Reliability grants",
        payees: [{ id: "p2", title: "Open Source Fund" }],
      },
    ],
    flowTasks: [
      "Application review",
      "Eligibility verification",
      "Payout processing",
      "Directory maintenance",
      "Review coordination",
      "FAQ support",
      "Tax documentation",
      "Stipend disbursement",
      "Impact reporting",
      "Cohort onboarding",
    ],
    roundTasks: [
      "Application grants",
      "Eligibility proposals",
      "Payment bounties",
      "Directory grants",
      "Review improvements",
      "Documentation bounties",
      "Compliance grants",
      "Tier proposals",
      "Metrics grants",
      "Outreach grants",
    ],
  },
  {
    id: "climate",
    label: "Climate",
    blurb: "Help households electrify and cut their carbon footprint.",
    goalTitle: "Get 1 million homes off fossil fuels",
    note: "Subgoals for electrification.",
    icon: Leaf,
    budgets: [
      "Build energy quiz",
      "Create cost calculator",
      "Map installer network",
      "Build rebate finder",
      "Write DIY guides",
      "Create contractor ratings",
      "Set up group buys",
      "Build progress tracker",
      "Create neighborhood guides",
      "Launch pilot program",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Installer coordination",
        payees: [{ id: "p1", title: "Electrify Crews" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Neighborhood pilot grants",
        payees: [{ id: "p2", title: "Block Captains" }],
      },
    ],
    flowTasks: [
      "Quiz maintenance",
      "Calculator updates",
      "Installer vetting",
      "Rebate tracking",
      "DIY content",
      "Rating moderation",
      "Group coordination",
      "Progress reporting",
      "Neighborhood outreach",
      "Pilot support",
    ],
    roundTasks: [
      "Quiz grants",
      "Calculator bounties",
      "Installer grants",
      "Rebate bounties",
      "DIY grants",
      "Review bounties",
      "Bulk experiments",
      "Tracking grants",
      "Community bounties",
      "Pilot grants",
    ],
  },
  {
    id: "aliens",
    label: "UFOs",
    blurb: "Back UAP research, open data, and citizen science.",
    goalTitle: "Declassify all UAP files",
    note: "Subgoals for transparency.",
    icon: Sparkles,
    budgets: [
      "Draft FOIA templates",
      "Build request tracker",
      "Create evidence database",
      "Set up citizen reports",
      "Map sighting hotspots",
      "Build analysis tools",
      "Recruit volunteer analysts",
      "Create press kit",
      "Organize witness interviews",
      "Plan first hearing",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Field research stream",
        payees: [{ id: "p1", title: "Skywatch Initiative" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Data transparency round",
        payees: [{ id: "p2", title: "Open Skies Lab" }],
      },
    ],
    flowTasks: [
      "FOIA filing",
      "Request tracking",
      "Evidence curation",
      "Report intake",
      "Hotspot monitoring",
      "Analysis pipeline",
      "Analyst coordination",
      "Media relations",
      "Interview scheduling",
      "Hearing prep",
    ],
    roundTasks: [
      "Template grants",
      "Tracker bounties",
      "Database grants",
      "Reporting grants",
      "Mapping bounties",
      "Analysis grants",
      "Training grants",
      "Press bounties",
      "Witness grants",
      "Hearing grants",
    ],
  },
  {
    id: "local-media",
    label: "Local Media",
    blurb: "Revive community journalism and public accountability.",
    goalTitle: "Put a reporter in every town",
    note: "Subgoals for local coverage.",
    icon: Radio,
    budgets: [
      "Build reporter directory",
      "Create pitch system",
      "Set up story database",
      "Build source manager",
      "Create style guide",
      "Set up fact-check flow",
      "Build publication tools",
      "Create training modules",
      "Set up tip line",
      "Launch first beats",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Reporting stream",
        payees: [{ id: "p1", title: "Civic Newsroom" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Community journalism round",
        payees: [{ id: "p2", title: "Local Media Lab" }],
      },
    ],
    flowTasks: [
      "Directory maintenance",
      "Pitch review",
      "Story archive",
      "Source verification",
      "Editorial standards",
      "Fact-check coordination",
      "Publishing support",
      "Training delivery",
      "Tip monitoring",
      "Beat coverage",
    ],
    roundTasks: [
      "Directory grants",
      "Pitch bounties",
      "Archive grants",
      "Source grants",
      "Style bounties",
      "Fact-check grants",
      "CMS bounties",
      "Curriculum grants",
      "Tip bounties",
      "Beat grants",
    ],
  },
] satisfies TopicConfig[];

export type TopicId = (typeof TOPICS)[number]["id"];

export const TOPIC_OPTIONS: GoalTopicOption<TopicId>[] = TOPICS.map(
  ({ id, label, blurb, icon }) => ({
    id,
    label,
    blurb,
    icon,
  })
);

export const TOPIC_BY_ID = Object.fromEntries(
  TOPICS.map((topic) => [topic.id, topic] as const)
) as Record<TopicId, TopicConfig>;

export function buildEvents(topic: TopicConfig): DaoEvent[] {
  const budgets = BUDGET_SCHEDULE.map((budget, index) => ({
    ...budget,
    title: topic.budgets[index] ?? topic.budgets[0],
  }));

  const budgetEvents = budgets.flatMap((budget) => [
    {
      t: budget.proposeAt,
      type: "BUDGET_PROPOSE" as const,
      id: budget.id,
      title: budget.title,
      minBudget: budget.minBudget,
      maxBudget: budget.maxBudget,
      fundingDeadline: budget.fundingDeadline,
      executionDuration: budget.executionDuration,
      by: budget.by,
    },
    {
      t: budget.resolveAt,
      type: "BUDGET_TCR_RESOLVE" as const,
      id: budget.id,
      result: "LISTED" as const,
    },
  ]);

  const stakeEvents = Object.entries(STAKE_PLAN).flatMap(([nodeId, events]) =>
    events.map((event) => ({
      t: event.t,
      type: "STAKE_WEIGHT_SET" as const,
      nodeId,
      actor: event.actor,
      weight: event.weight,
    }))
  );

  const mechEvents = topic.mechs.flatMap((mech, index) => [
    {
      t: 35 + index,
      type: "MECH_PROPOSE" as const,
      id: mech.id,
      parentBudgetId: "b1",
      mechType: mech.mechType,
      title: mech.title,
      payees: mech.payees,
      by: "system" as const,
    },
    {
      t: 37 + index,
      type: "MECH_TCR_RESOLVE" as const,
      id: mech.id,
      result: "LISTED" as const,
    },
  ]);

  const events: DaoEvent[] = [
    { t: 0, type: "GOAL_CREATE", id: "g1", title: topic.goalTitle, deadline: 70, by: "human1" },
    { t: 0, type: "GOAL_DEPOSIT", from: "donor", amount: 100_000 },
    { t: 2, type: "NOTE", text: topic.note },
    ...budgetEvents,
    ...stakeEvents,
    { t: 18, type: "GOAL_DEPOSIT", from: "donor", amount: 20_000 },
    { t: 34, type: "NOTE", text: "Subgoal funded." },
    ...mechEvents,
    { t: 39, type: "STAKE_WEIGHT_SET", nodeId: "m1", actor: "human1", weight: 15 },
    { t: 40, type: "STAKE_WEIGHT_SET", nodeId: "m2", actor: "bot1", weight: 10 },
    { t: 41, type: "PAYEE_ADD", mechId: "m1", actor: "human1" },
    { t: 41.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 42, type: "PAYEE_ADD", mechId: "m2", actor: "human2" },
    { t: 42.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 43, type: "PAYEE_ADD", mechId: "m1", actor: "human1" },
    { t: 43.5, type: "PAYEE_ADD", mechId: "m2", actor: "bot1" },
    { t: 44, type: "PAYEE_ADD", mechId: "m1", actor: "human2" },
    { t: 44.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 45, type: "PAYEE_ADD", mechId: "m2", actor: "human1" },
    { t: 45.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 46, type: "PAYEE_ADD", mechId: "m1", actor: "human2" },
    { t: 46.5, type: "PAYEE_ADD", mechId: "m2", actor: "bot1" },
    { t: 47, type: "PAYEE_ADD", mechId: "m1", actor: "human1" },
    { t: 47.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 48, type: "PAYEE_ADD", mechId: "m2", actor: "human2" },
    { t: 48.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 49, type: "STAKE_WEIGHT_SET", nodeId: "b1", actor: "human1", weight: 0 },
    { t: 50, type: "NOTE", text: "Stake removed." },
    { t: 51, type: "PAYEE_ADD", mechId: "m1", actor: "human1" },
    { t: 52, type: "PAYEE_ADD", mechId: "m2", actor: "bot1" },
    { t: 53, type: "PAYEE_ADD", mechId: "m1", actor: "human2" },
    { t: 54, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 55, type: "PAYEE_REMOVE", mechId: "m1", actor: "bot1" },
    { t: 56, type: "PAYEE_REMOVE", mechId: "m2", actor: "human1" },
    { t: 57, type: "NOTE", text: "Subgoal funded (cap soon)." },
    { t: 59, type: "BUDGET_RESOLVE", id: "b1", result: "SUCCEEDED" },
    { t: 61, type: "NOTE", text: "Subgoal completed." },
    { t: 64, type: "BUDGET_RESOLVE", id: "b3", result: "FAILED" },
    { t: 67, type: "NOTE", text: "Goal verified." },
    { t: 69, type: "GOAL_RESOLVE", result: "SUCCEEDED" },
  ];

  return events;
}
