import { Users, HeartPulse, ShieldCheck, Code, Leaf, Sparkles, Radio } from "lucide-react";
import type { GoalTopicOption } from "@/components/common/goal-topic-toggle";
import type { DaoEvent } from "@/components/visuals/dao-flow-diagram/dao-flow-diagram";
import type { BudgetTemplate, StakePlan, TopicConfig } from "./types";

const BUDGET_SCHEDULE = [
  {
    id: "b1",
    proposeAt: 5,
    resolveAt: 8,
    minBudget: 12_000,
    maxBudget: 30_000,
    fundingDeadline: 25,
    executionDuration: 60,
    by: "human1",
  },
  {
    id: "b2",
    proposeAt: 6,
    resolveAt: 9,
    minBudget: 8_000,
    maxBudget: 18_000,
    fundingDeadline: 25,
    executionDuration: 60,
    by: "bot1",
  },
  {
    id: "b3",
    proposeAt: 7,
    resolveAt: 10,
    minBudget: 8_000,
    maxBudget: 14_000,
    fundingDeadline: 50,
    executionDuration: 55,
    by: "human2",
  },
  {
    id: "b4",
    proposeAt: 11,
    resolveAt: 13,
    minBudget: 5_000,
    maxBudget: 12_000,
    fundingDeadline: 40,
    executionDuration: 50,
    by: "bot1",
  },
  {
    id: "b5",
    proposeAt: 12,
    resolveAt: 14,
    minBudget: 7_000,
    maxBudget: 16_000,
    fundingDeadline: 45,
    executionDuration: 55,
    by: "human1",
  },
] satisfies BudgetTemplate[];

const STAKE_PLAN: StakePlan = {
  b1: [
    { t: 8, actor: "human1", weight: 20 },
    { t: 9, actor: "bot1", weight: 20 },
    { t: 10, actor: "bot1", weight: 20 },
  ],
  b2: [
    { t: 12, actor: "bot1", weight: 20 },
    { t: 13, actor: "human2", weight: 20 },
    { t: 14, actor: "bot1", weight: 20 },
  ],
  b3: [
    { t: 11, actor: "human2", weight: 20 },
    { t: 12, actor: "human1", weight: 20 },
    { t: 13, actor: "bot1", weight: 20 },
  ],
  b4: [
    { t: 17, actor: "bot1", weight: 20 },
    { t: 18, actor: "human1", weight: 20 },
    { t: 19, actor: "bot1", weight: 20 },
  ],
  b5: [
    { t: 20, actor: "human2", weight: 20 },
    { t: 21, actor: "bot1", weight: 20 },
    { t: 22, actor: "human1", weight: 20 },
  ],
};

export const TOPICS = [
  {
    id: "dao",
    label: "DAO",
    blurb: "Build open-source operating software for member-owned internet communities.",
    goalTitle: "Build DAO Operator OS",
    note: "Budgets for governance, treasury, and contributor operations.",
    icon: Users,
    budgets: [
      "Safe + treasury cockpit",
      "Proposal drafting workspace",
      "Vote simulation sandbox",
      "Contributor reputation graph",
      "Working group dashboard",
      "Dispute resolution console",
      "Onchain payout queue",
      "Member onboarding portal",
      "Community ops bot",
      "Governance analytics",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Maintainer stream",
        payees: [{ id: "p1", title: "DAO Core Maintainers" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Plugin builder round",
        payees: [{ id: "p2", title: "Extension Builders" }],
      },
    ],
    flowTasks: [
      "Treasury maintenance",
      "Proposal tooling",
      "Simulation upkeep",
      "Reputation tuning",
      "Dashboard ops",
      "Dispute triage",
      "Payout review",
      "Onboarding support",
      "Bot maintenance",
      "Analytics reporting",
    ],
    roundTasks: [
      "Plugin grants",
      "Workflow bounties",
      "Voting experiments",
      "Reputation grants",
      "Dashboard modules",
      "Arbitration tools",
      "Payout automation",
      "Onboarding kits",
      "Ops bot plugins",
      "Analytics add-ons",
    ],
  },
  {
    id: "longevity",
    label: "Longevity",
    blurb: "Build open-source health software for tracking experiments, labs, and recovery.",
    goalTitle: "Build Open Health OS",
    note: "Budgets for shipping and maintaining the product.",
    icon: HeartPulse,
    budgets: [
      "Health timeline",
      "Lab import adapters",
      "Wearables sync",
      "Meal photo parser",
      "Experiment notebook",
      "Local AI health assistant",
      "Clinician export",
      "Security review",
      "Onboarding docs",
      "Beta cohort support",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Maintainer stream",
        payees: [{ id: "p1", title: "Open Health Maintainers" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Research plugin round",
        payees: [{ id: "p2", title: "Longevity Builders" }],
      },
    ],
    flowTasks: [
      "Timeline maintenance",
      "Lab integrations",
      "Wearables support",
      "Nutrition parsing",
      "Experiment tooling",
      "Assistant tuning",
      "Export reliability",
      "Security patching",
      "Docs upkeep",
      "Cohort operations",
    ],
    roundTasks: [
      "Integration grants",
      "Research plugins",
      "Parser bounties",
      "Notebook experiments",
      "Assistant prompts",
      "Export add-ons",
      "Security audits",
      "Docs improvements",
      "Cohort tooling",
      "Biofeedback modules",
    ],
  },
  {
    id: "privacy",
    label: "Privacy",
    blurb: "Build open-source privacy software for safer messaging, storage, and coordination.",
    goalTitle: "Build Privacy Coordination Stack",
    note: "Budgets for secure onboarding, migration, and daily use.",
    icon: ShieldCheck,
    budgets: [
      "Signal migration assistant",
      "Encrypted shared workspace",
      "Private file drop",
      "Key backup flow",
      "Threat model wizard",
      "Group onboarding guide",
      "Moderation safety console",
      "Mobile hardening kit",
      "Red-team review",
      "Emergency recovery docs",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Security maintainer stream",
        payees: [{ id: "p1", title: "Privacy Maintainers" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Community hardening round",
        payees: [{ id: "p2", title: "Security Builders" }],
      },
    ],
    flowTasks: [
      "Migration support",
      "Workspace maintenance",
      "File-drop ops",
      "Backup reliability",
      "Threat-model updates",
      "Onboarding support",
      "Safety tooling",
      "Mobile hardening",
      "Security patching",
      "Recovery docs",
    ],
    roundTasks: [
      "Migration grants",
      "Workspace plugins",
      "Safety audits",
      "Backup experiments",
      "Threat-model templates",
      "Onboarding kits",
      "Moderation tools",
      "Device hardening guides",
      "Red-team bounties",
      "Recovery drills",
    ],
  },
  {
    id: "open-source",
    label: "Open Source",
    blurb: "Build open-source software that keeps maintainers fast, funded, and sane.",
    goalTitle: "Build Maintainer OS",
    note: "Budgets for review, release, and project stewardship.",
    icon: Code,
    budgets: [
      "Issue triage inbox",
      "PR review queue",
      "Release automation",
      "Dependency risk monitor",
      "Funding dashboard",
      "Contributor onboarding",
      "Docs maintenance kit",
      "Crash + regression triage",
      "Project health analytics",
      "Maintainer handoff tools",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Stewardship stream",
        payees: [{ id: "p1", title: "Core Maintainers" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Reliability round",
        payees: [{ id: "p2", title: "Ecosystem Builders" }],
      },
    ],
    flowTasks: [
      "Issue triage",
      "Review operations",
      "Release support",
      "Dependency monitoring",
      "Funding ops",
      "Contributor support",
      "Docs upkeep",
      "Regression triage",
      "Health reporting",
      "Handoff maintenance",
    ],
    roundTasks: [
      "Triage plugins",
      "Review tooling",
      "Release add-ons",
      "Security grants",
      "Funding experiments",
      "Onboarding kits",
      "Docs automation",
      "QA bounties",
      "Metrics modules",
      "Handoff tools",
    ],
  },
  {
    id: "climate",
    label: "Climate",
    blurb: "Build open-source software that helps homes and neighborhoods electrify faster.",
    goalTitle: "Build Home Electrify OS",
    note: "Budgets for planning, quoting, and neighborhood deployment.",
    icon: Leaf,
    budgets: [
      "Home retrofit planner",
      "Heat pump quote comparer",
      "Rebate tracker",
      "Installer map",
      "Solar + battery modeler",
      "Permit checklist builder",
      "Neighborhood group-buy tools",
      "Utility bill parser",
      "Contractor scorecards",
      "Electrification playbook",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Maintainer stream",
        payees: [{ id: "p1", title: "Electrify Maintainers" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Local deployment round",
        payees: [{ id: "p2", title: "Climate Builders" }],
      },
    ],
    flowTasks: [
      "Planner maintenance",
      "Quote tooling",
      "Rebate updates",
      "Installer verification",
      "Model upkeep",
      "Permit guidance",
      "Group-buy ops",
      "Bill parsing",
      "Scorecard moderation",
      "Playbook support",
    ],
    roundTasks: [
      "Planner grants",
      "Quote integrations",
      "Rebate adapters",
      "Installer data tools",
      "Model improvements",
      "Permit templates",
      "Bulk-buy modules",
      "Bill parser bounties",
      "Review experiments",
      "Playbook translations",
    ],
  },
  {
    id: "aliens",
    label: "UFOs",
    blurb: "Build open-source software for UAP archives, sensor data, and collaborative analysis.",
    goalTitle: "Build the Open Sky Archive",
    note: "Budgets for ingesting sightings, evidence, and sensor data.",
    icon: Sparkles,
    budgets: [
      "Sighting intake portal",
      "Case archive",
      "Sensor upload pipeline",
      "Video analysis tools",
      "FOIA document parser",
      "Witness interview workspace",
      "Map of incident clusters",
      "Chain-of-custody logs",
      "Research publication site",
      "Public API",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Archive maintainer stream",
        payees: [{ id: "p1", title: "Open Sky Maintainers" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Analysis tool round",
        payees: [{ id: "p2", title: "Citizen Researchers" }],
      },
    ],
    flowTasks: [
      "Intake moderation",
      "Archive maintenance",
      "Sensor ingestion",
      "Video tooling",
      "Document parsing",
      "Interview support",
      "Cluster mapping",
      "Evidence logging",
      "Publishing ops",
      "API upkeep",
    ],
    roundTasks: [
      "Intake grants",
      "Archive plugins",
      "Sensor adapters",
      "Analysis bounties",
      "Parser grants",
      "Interview tools",
      "Mapping modules",
      "Evidence standards",
      "Publishing templates",
      "API integrations",
    ],
  },
  {
    id: "local-media",
    label: "Local Media",
    blurb: "Build open-source newsroom software for local reporting and public accountability.",
    goalTitle: "Build Local Newsroom Stack",
    note: "Budgets for sourcing, publishing, and community distribution.",
    icon: Radio,
    budgets: [
      "Source inbox",
      "Beat planning board",
      "Records request tracker",
      "Fact-check workspace",
      "Public tip line",
      "Story budget dashboard",
      "Neighborhood alert feed",
      "Publisher CMS",
      "Audio + transcript tools",
      "Reader membership portal",
    ],
    mechs: [
      {
        id: "m1",
        mechType: "FLOW",
        title: "Newsroom maintainer stream",
        payees: [{ id: "p1", title: "Civic News Maintainers" }],
      },
      {
        id: "m2",
        mechType: "ROUND",
        title: "Community tools round",
        payees: [{ id: "p2", title: "Local Media Builders" }],
      },
    ],
    flowTasks: [
      "Source moderation",
      "Beat planning",
      "Records tracking",
      "Fact-check ops",
      "Tipline support",
      "Budget maintenance",
      "Alert publishing",
      "CMS upkeep",
      "Transcript tooling",
      "Membership support",
    ],
    roundTasks: [
      "Sourcing grants",
      "Planning plugins",
      "FOIA tools",
      "Fact-check add-ons",
      "Tipline bounties",
      "Budget data modules",
      "Alert feed integrations",
      "Publishing templates",
      "Audio workflow tools",
      "Membership experiments",
    ],
  },
] satisfies TopicConfig[];

export type TopicId = (typeof TOPICS)[number]["id"];

export const TOPIC_OPTIONS: GoalTopicOption<TopicId>[] = TOPICS.map(
  ({ id, label, blurb, icon }) => ({
    id,
    label,
    blurb,
    icon,
  })
);

export const TOPIC_BY_ID = Object.fromEntries(
  TOPICS.map((topic) => [topic.id, topic] as const)
) as Record<TopicId, TopicConfig>;

export function buildEvents(topic: TopicConfig): DaoEvent[] {
  const budgets = BUDGET_SCHEDULE.map((budget, index) => ({
    ...budget,
    title: topic.budgets[index] ?? topic.budgets[0],
  }));

  const budgetEvents = budgets.flatMap((budget) => [
    {
      t: budget.proposeAt,
      type: "BUDGET_PROPOSE" as const,
      id: budget.id,
      title: budget.title,
      minBudget: budget.minBudget,
      maxBudget: budget.maxBudget,
      fundingDeadline: budget.fundingDeadline,
      executionDuration: budget.executionDuration,
      by: budget.by,
    },
    {
      t: budget.resolveAt,
      type: "BUDGET_TCR_RESOLVE" as const,
      id: budget.id,
      result: "LISTED" as const,
    },
  ]);

  const stakeEvents = Object.entries(STAKE_PLAN).flatMap(([nodeId, events]) =>
    events.map((event) => ({
      t: event.t,
      type: "STAKE_WEIGHT_SET" as const,
      nodeId,
      actor: event.actor,
      weight: event.weight,
    }))
  );

  const mechEvents = topic.mechs.flatMap((mech, index) => [
    {
      t: 35 + index,
      type: "MECH_PROPOSE" as const,
      id: mech.id,
      parentBudgetId: "b1",
      mechType: mech.mechType,
      title: mech.title,
      payees: mech.payees,
      by: "system" as const,
    },
    {
      t: 37 + index,
      type: "MECH_TCR_RESOLVE" as const,
      id: mech.id,
      result: "LISTED" as const,
    },
  ]);

  const events: DaoEvent[] = [
    { t: 0, type: "GOAL_CREATE", id: "g1", title: topic.goalTitle, deadline: 70, by: "human1" },
    { t: 0, type: "GOAL_DEPOSIT", from: "donor", amount: 100_000 },
    { t: 2, type: "NOTE", text: topic.note },
    ...budgetEvents,
    ...stakeEvents,
    { t: 18, type: "GOAL_DEPOSIT", from: "donor", amount: 20_000 },
    { t: 34, type: "NOTE", text: "Subgoal funded." },
    ...mechEvents,
    { t: 39, type: "STAKE_WEIGHT_SET", nodeId: "m1", actor: "human1", weight: 15 },
    { t: 40, type: "STAKE_WEIGHT_SET", nodeId: "m2", actor: "bot1", weight: 10 },
    { t: 41, type: "PAYEE_ADD", mechId: "m1", actor: "human1" },
    { t: 41.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 42, type: "PAYEE_ADD", mechId: "m2", actor: "human2" },
    { t: 42.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 43, type: "PAYEE_ADD", mechId: "m1", actor: "human1" },
    { t: 43.5, type: "PAYEE_ADD", mechId: "m2", actor: "bot1" },
    { t: 44, type: "PAYEE_ADD", mechId: "m1", actor: "human2" },
    { t: 44.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 45, type: "PAYEE_ADD", mechId: "m2", actor: "human1" },
    { t: 45.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 46, type: "PAYEE_ADD", mechId: "m1", actor: "human2" },
    { t: 46.5, type: "PAYEE_ADD", mechId: "m2", actor: "bot1" },
    { t: 47, type: "PAYEE_ADD", mechId: "m1", actor: "human1" },
    { t: 47.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 48, type: "PAYEE_ADD", mechId: "m2", actor: "human2" },
    { t: 48.5, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 49, type: "STAKE_WEIGHT_SET", nodeId: "b1", actor: "human1", weight: 0 },
    { t: 50, type: "NOTE", text: "Stake removed." },
    { t: 51, type: "PAYEE_ADD", mechId: "m1", actor: "human1" },
    { t: 52, type: "PAYEE_ADD", mechId: "m2", actor: "bot1" },
    { t: 53, type: "PAYEE_ADD", mechId: "m1", actor: "human2" },
    { t: 54, type: "PAYEE_ADD", mechId: "m1", actor: "bot1" },
    { t: 55, type: "PAYEE_REMOVE", mechId: "m1", actor: "bot1" },
    { t: 56, type: "PAYEE_REMOVE", mechId: "m2", actor: "human1" },
    { t: 57, type: "NOTE", text: "Subgoal funded (cap soon)." },
    { t: 59, type: "BUDGET_RESOLVE", id: "b1", result: "SUCCEEDED" },
    { t: 61, type: "NOTE", text: "Subgoal completed." },
    { t: 64, type: "BUDGET_RESOLVE", id: "b3", result: "FAILED" },
    { t: 67, type: "NOTE", text: "Goal verified." },
    { t: 69, type: "GOAL_RESOLVE", result: "SUCCEEDED" },
  ];

  return events;
}
