import { COBUILD_JUICEBOX_PROJECT_ID } from "@/lib/domains/token/juicebox/constants";
import {
  REVNET_ISSUANCE_MAX_HORIZON_YEARS,
  REVNET_SECONDS_PER_DAY,
  REVNET_SECONDS_PER_YEAR,
  REVNET_WEIGHT_CUT_SCALE,
  REVNET_WEIGHT_SCALE,
} from "@cobuild/wire";

export const PROJECT_ID = COBUILD_JUICEBOX_PROJECT_ID;

export const WEIGHT_SCALE = REVNET_WEIGHT_SCALE;
export const WEIGHT_CUT_SCALE = REVNET_WEIGHT_CUT_SCALE;
export const SECONDS_PER_DAY = REVNET_SECONDS_PER_DAY;
export const SECONDS_PER_YEAR = REVNET_SECONDS_PER_YEAR;
export const MAX_HORIZON_YEARS = REVNET_ISSUANCE_MAX_HORIZON_YEARS;
