export const REWARDS = {
  TOTAL_POOL_USD: 100,
  AI_DUELS_SHARE: 0.5,
  QUADRATIC_SHARE: 0.5,
} as const;

export const AI_DUELS_POOL_USD = REWARDS.TOTAL_POOL_USD * REWARDS.AI_DUELS_SHARE;
export const QUADRATIC_POOL_USD = REWARDS.TOTAL_POOL_USD * REWARDS.QUADRATIC_SHARE;
